### ISSUE TITLE
Missing Sensor Behavior 

### ISSUE THREAD

**Issue by xundre** [toggledbits/DelayLight#15]
I have a motion sensor which isn't always online as it is in a camera powered off when house in "Home" mode. Problem is while off , the delayed sensor trigger still fires which it should not when sensor is missing.

**Comment by toggledbits** [comment]
Well, somehow that your sensor device is still changing state. Devices that are "off line" or "missing" don't usually spontaneously change state in the Vera world, and I don't think it's an unreasonable expectation of DelayLight for the sensor to behave consistently with other devices. And if the sensor is actually "missing," then it would likely get a new device ID when it comes back, and that would break your configuration anyway. I'd guess that perhaps "hidden" is more likely, but DelayLight doesn't care about that.

Failing figuring out what it going on with your sensor, you could configure your DelayLightTimer to be active only in house modes other than Home; that way, the sensor will be ignored when it is supposed to be "missing."
