### ISSUE TITLE
Add a level on inhibitors

### ISSUE THREAD

**Issue by vosmont** [toggledbits/DelayLight#16]
Hello @toggledbits,

would it be possible to have a level option on inhibitors?
The idea: 
- If the loadLevel of the device is above: the timer is not activated
- With the checkbox "Invert", if the loadlevel is bellow, the time can be activated.

I would also like to be able to define light sensor as inhibitor.

**Comment by toggledbits** [comment]
I hear you, but it's requests like this that are exactly why I wrote Reactor. Dead on. As the requests started to roll in for different triggering options (and inhibits) on DelayLight, it occurred to me that I would never be able to address everything everyone wanted to do in that interface with adding considerable heft to the plugin and complexity to its interface. Every device, including plugins, was a potential target for some use as a trigger (e.g. turn off my lights 30 seconds after the AV receiver is switched to HDMI3). As I started to think about a generic, rules-based approach, it wasn't long before I reasoned that a better rules engine would be useful in a lot of contexts, not just driving light timing. And that's when Reactor was born.

So, Reactor is the solution for this. You can use a ReactorSensor directly as a trigger or inhibitor in DelayLight.
